# Change these first
owner: handokoaji
repo: monitor
baseUrl: /monitor

sites:
  - name: DEV
    url: http://peta-inovasi.dev.handokoaji.my.id/
    expectedStatusCodes:
      - 200

status-website:
  # CNAME dikosongkan/comment karena tidak pakai custom domain
  # cname: monitor.handokoaji.my.id
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Monitor Ketua** powered entirely by GitHub & Upptime."
  introMessage: Monitor yang bisa dimonitor
  navbar:
    - title: Status
      href: /monitor/
    - title: GitHub
      href: https://github.com/handokoaji/monitor

notifications:
  - type: telegram
    chatId: $TELEGRAM_CHAT_ID
    botToken: $TELEGRAM_BOT_TOKEN
