# Change these first
owner: handokoaji
repo: monitor
baseUrl: /monitor

sites:
  - name: DEV
    url: https://peta-inovasi.handokoaji.my.id
    expectedStatusCodes:
      - 200

status-website:
  # PINDAHKAN baseUrl KE SINI (di dalam status-website)
  baseUrl: /monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Monitor Ketua** powered entirely by GitHub & Upptime."
  introMessage: Monitor yang bisa dimonitor
  navbar:
    - title: Status
      href: /monitor/
    - title: GitHub
      href: https://github.com/handokoaji/monitor

notifications:
  - type: telegram
    # Upptime akan otomatis mengambil SECRET dari GitHub Actions 
    # Pastikan Nama Secret di GitHub adalah: NOTIFICATION_TELEGRAM_BOT_KEY dan NOTIFICATION_TELEGRAM_CHAT_ID
