# Change these first
owner: handokoaji # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: DEV
    url: http://peta-inovasi.dev.handokoaji.my.id/
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.handokoaji.my.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Monitor Ketua** powered entirely by GitHub & Upptime."
  introMessage: Monitor yang bisa dimonitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: telegram
    chatId: $TELEGRAM_CHAT_ID
    botToken: $TELEGRAM_BOT_TOKEN

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
